### PR TITLE
cleanups + convert ids to long

### PR DESCRIPTION
**Pull request by timelessnesses**

### CODE REVIEW

**Comment by timelessnesses** [comment]
why did vs added signing cert there?

**Comment by qfoxb** [comment]
compiling a user wearing an ID over the max integer results in this error 
image

**Comment by qfoxb** [comment]
user was Roblox so ID 1

**Comment by timelessnesses** [comment]
wtf

**Comment by timelessnesses** [comment]
```cs
int index = bone.NameIndex;
                    int parentId = bone.ParentId;

                    var buffer = new List<byte>();
                    while (true)
                    {
                        if (nameTable.Length <= 0) break; //my own modification
                        System.Console.WriteLine(index);// also my own modification
                   >>>> byte next = nameTable[index];

                        if (next > 0)
                            index++;
                        else
                            break;

                        buffer.Add(next);
                    }
```
bone's name index somehow is more than what the name table had (in this case name table had 1 element while the bone's name index is 4000+

**Comment by qfoxb** [comment]
what does that code sample fix

**Comment by timelessnesses** [comment]
note that there's also "conversion error" in roblox file format.
looks like it need to be updated too

**Comment by timelessnesses** [comment]
> what does that code sample fix

its not a fix but its where error originated from

**Comment by qfoxb** [comment]
could this have something to do with the fact that roblox is wearing an animated face, can you try to find another user wearing an item with id greater than 32 bit integer to see if it's just that or because of the animated face

**Comment by qfoxb** [comment]
if it's the animated face, i'll add that to known issues unless you can figure out how to fix it.

**Comment by timelessnesses** [comment]
done testing you can use my username (python_mooping) to test (it have 64 bits t shirt asset id)

**Comment by timelessnesses** [comment]
added it back

**Pull request merged**
